### ISSUE TITLE
0 dyld_fatal_error

### ISSUE THREAD

**Issue by mosspassion** [genekogan/KinectOSC#2]
Hello,

@genekogan thanks for responding to [my comment](https://github.com/ccerhan/ofxOpenNI/commit/e6cbc5143d0542e7a80133202f8daaa23cb41487) on @ccerhan's ofxOpenNI repo. As you suggested, I took Xcode's suggestions of replacing `ofGetGLTypeFromPixelFormat()` with `ofGetGLFormatFromPixelFormat()`, and I am now getting a successful build in debug mode, but afterwards I'm getting caught at a breakpoint `KinectOSC -> Thread 1 -> 0 dyld_fatal_error`.

I have to admit that I am a little confused by what you mean in your `KinectOSC` readme when you say 

> Make sure you follow the instructions in ofxOpenNI to include the openni config folder in the data folder of the application, which has been omitted from this repository because of space considerations.

So, I haven't included any folder anywhere.

Other than that, I think I have followed all other instructions well.

I'm using Xcode 8.1, OS X 10.11.6, OpenFrameworks 0.9.7. 

Thank you for your hard work (this isn't the first time I've used one of your repos for something)!

**Comment by mosspassion** [comment]
Well, upon further investigation of how to install the openni config folder data, I got everything to work. At the moment it is working with @ccerhan's ofxOpenNI repo (the one with a lot of deprecated methods updated for OFv0.9.x). I followed the instructions in the readme of the @gameoverhack [repo](https://github.com/gameoverhack/ofxOpenNI/), specifically the part about how to get the examples to work:

> Mac OS X:
> 
> You don't need to do any install of drivers if you don't want, just:
> 
> ```
> Do the git magic above or somehow else get a copy of ofxOpenNI into your addons directory
> Copy 'example' folder to yourofdir/apps/yourworkingdir
> Copy the folder called 'lib' from 'ofxOpenNI/mac/copy_to_data_openni_path' to your 'bin/data/openni' directory of your example.
> Rename or copy one of the src-SomeExample-Level (eg., src-UserAndCloud-Medium) to just 'src'
> You might need to clean before building each time you change the src folder
> ```

Yep, I derped. I hope my derp can prevent other derps from derping like I did. (read the installation instructions thoroughly)

Thanks Gene!

**Comment by genekogan** [comment]
yeah the whole process is a little convoluted, but good to hear you got it working.
